services:
  backend:
    build: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend
    depends_on:
      - ollama
      - db
    networks:
      - testing-network
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/magic_db

  db:
      image: postgres:latest
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: magic_db
      volumes:
        - pgdb:/var/lib/postgresql/data/
      ports:
        - "5432:5432"
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 30s
        timeout: 10s
        retries: 5

  frontend:
    build: frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    networks:
      - testing-network

  ollama:
    build: ollama
    ports: 
      - 11434:11434
    volumes:
      - test-vol:/ollama
    networks:
      - testing-network
    entrypoint: ['/usr/bin/bash', '/pull-llama3.sh']

networks:
  testing-network:
    driver: bridge

volumes:
  test-vol:
    driver: local
  pgdb: